terraform {
  required_version = ">= 1.11" # needed for the S3 backend's native use_lockfile locking

  # Values (bucket/key/region) come from backend.hcl at init time — see
  # backend.hcl.example and infra/README.md. They can't be hardcoded here
  # because the bucket name includes a random suffix generated by bootstrap/.
  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
